spring:
  profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: cEb34CCddb6G1FFDccD-A-B3FF5h-1-E
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:11040/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    logging:
      level:
        org:
          springframework:
            core:
              env=DEBUG:

