name: Mart Application CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Update submodules
        run: git submodule update --remote

      - name: Set executable permission for Maven wrapper
        run: chmod +x ./Backend/mart/mvnw

      - name: Build with Maven
        run: ./Backend/mart/mvnw -ntp verify

